CREATE TABLE `persons` (
	`id` INT(11) UNIQUE NOT NULL AUTO_INCREMENT,
	`last_name` VARCHAR(255) CHARACTER SET utf8 NOT NULL,
	`first_name` VARCHAR(255) CHARACTER SET utf8 NOT NULL,
	`born_name` VARCHAR(255) CHARACTER SET utf8 NULL DEFAULT NULL,
	`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
